name: Publish @voidfull/js-sdk

on:
  release:
    types: [created]

env:
  node_version: 20

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Build
        run: |
          pnpm i --frozen-lockfile --prod=false
          pnpm --filter @voidfull/js-sdk build

      - name: Set publishing config
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.PKG_JS_SDK_NPM_TOKEN}}

      - run: |
          pnpm --filter @voidfull/js-sdk publish --no-git-checks
